spring.application.name=Baseera

#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#DB_URL=jdbc:mysql://localhost:3306/BaseeraDB?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
#DB_USERNAME=root
#DB_PASSWORD=Muneera@2026
spring.datasource.url=jdbc:mysql://localhost:3306/BaseeraDB?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Muneera@2026
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- New settings for JWT (add these) ---
# The secret key used to sign tokens (explained in Part 5)
jwt.secret=ThisIsASecretKeyForJwtThatMustBeAtLeast32CharsLong 
jwt.expiration=3600000

